# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env update -f ci/hera_cc_utils_tests.yml --name base
    - name: Lint with flake8 + black
      run: |
        pre-commit run -a
    - name: Build
      run: |
        pip install .
        echo "backend : Agg" > $HOME/matplotlibrc
        export MATPLOTLIBRC=$HOME
    - name: Test with pytest
      run: |
        pytest --cov-config=.coveragerc --cov=hera_cc_utils --cov-report=xml -v tests/*.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
        name: codecov-hera_cc_utils
        verbose: true
